### ISSUE TITLE
Links for ReproZip are very out of date

### ISSUE THREAD

**Issue by remram44** [ResearchObject/ResearchObject.github.io#1]
Hi,

I noticed that the pages on ReproZip both [on www.researchobject.org](http://www.researchobject.org/initiative/reprozip/) and [on researchobject.github.io](http://researchobject.github.io/initiative/reprozip/) seem outdated. They point to reprozip `0.1.0-beta` and [this page on the NYU CDS website](https://cds.nyu.edu/projects/reprozip/) (which describes newer ReproZip versions, rewritten from scratch in 2014).

The correct website should be [www.reprozip.org](https://www.reprozip.org/) (which also lists [our preferred citation](https://www.reprozip.org/about.html#cite)).

**Comment by stain** [comment]
Thanks, I added the citation as well. BTW, the DOI <https://doi.org/10.1145/2882903.2899401> is missing from your website so I included that as well.
